language: node_js
node_js:
- '7'
install:
- yarn
- yarn run lint
cache:
  yarn: true
deploy:
  provider: cloudfoundry
  api: https://api.system.titan.lab.emc.com
  username: ahernd2
  password:
    secure: lV3ga/LNj+BHz/U2m2hETn/6Iar5vPqxOvt5wL/E7kd6mgSD4VYQ5eLM0VMajmeiRN90EJXOJ/B9d2/iPxJ7vWN+tJRVo2ygb5Rjl+oAWhNogfuwvYdIlyCABYY134CMbGIScInCfAJ4QU1734wH7EjHdjC2h6axPbSyiR1oXNqkCMDdZ6UOsI2sR8u0/KmK21OYKIWBNp6KtYemzPDfmkxPcC/W3usRVUZgAC87/cD9BR2uu8I5W72qlUJMPm95SZ/qi1UczsQmI9gILwaXQGwWkgsSkJK9uMYExWEeeBH1ZJzbxSojDUbTL1Gd9zMBiKC02aSK085FZDu2MlveNVJA2oY4rVmHotpIrw4vZla59EvRRXWTPtc4IfxqYYlZZEmRfhHAfbu9lgjw1OnHOqFGijlukPiBIFV+HFcVrKttAgKwWNjdKWlJEFutiMEnMYOb1315w70ZnBR7FHNt3pA8nSqKtAmL+tuH0yqW0f5tsCLOvjRu2oRjZX71yFY82kO3EQPMrG8yOYSO9qP4lwd1n1EvlFwsE/3hccky2fWtY1pnqvz/eGvV/LQzQeSTKDYV4ijuvSvdP50OJgQOF7kAbQEiWzcP8KhvKN8PC+ixUrwbCbD2K77mnKDNhWTv4IQ3tumyYuKHwYSqhYimBP6HK297zr1rcsWLJ7dxM1c=
  organization: thor
  space: prod
  on:
    repo: el-davo/linkcouch-screenshots-backend
