language: node_js
node_js:
- '7'
install:
- yarn
- yarn run lint
cache:
  yarn: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: david.ahern26@gmail.com
  password:
    secure: qcAbL2LkHbeeaTDwIVPuF6c21p5gYQA5vLRTGPbBDilgmKBtqAPSb7ftaC72ypThF6lh65NugkIEi35kJA4aEWorGq8n2Svm2vj/F+XzHAllcbnz2RpToO5wSrjALH7RI29yD2FnbVOPzG2Me3ciq0jT/Y8LO2RzUX0Psp/pR6ILhUvch+7LCxEwXLe0KqlOeSTub96Ehd78lZ8jXsLYxMhrKSoCzdW/MbEDuwdWG90TGrr2GdDHQkkMe17ZTwtGW2D1u4IiyEfaX8h7pBbRbevbFmNJqSzxKHLq4UrPJI1LT5OvwER4dHnIa5rCSuxJOPFgdQNgO5BqgboAdje8pZH7ZOVwrvfdIUwhxZKFBRId+XbE+DfzOqkTNhyVnnBER0eL4+19SjI4yoL8CVr7R1SIzOawH67HuJ4G6kcEisSDKx9bLbiqcvBVG3OYpX+xCOozLAOW0PSsvFAzF64e7/IzM0VA/UwSuETwoKmArlP39WSR4Yz/oOLi43p8x6N5WXqDSv4SEYy2i+xZ6bbYDN8K7yfCBYVA1kSWli+fuCU1WdHFuBcfXVQOTjvjPIgOBO6WcOo8FBy0col+b65G0uqAT/ihsRCDvxRvr8QUIqriao9hQK+A17Am7+VZsphp7IhBPDKnTFqVa+gu3ocFoAIA1DoJpka7ALaUsgI9FLc=
  organization: thor
  space: prod
  on:
    branch: master
