language: node_js
node_js:
- '7'
install:
- yarn
- yarn run lint
cache:
  yarn: true
deploy:
  provider: cloudfoundry
  api: https://api.system.titan.lab.emc.com
  username: david.ahern26@gmail.com
  password:
    secure: lxDQM0hlopaeFDpaVh82YunaTV+FHSKvdzPy0FBx4VkUMcmktcm2e2SSB/D530tGvmw6455X4mL7lWWu8O3y2vFo9WSmREIje5A9Q4LmITPiQtXqSrDrRXqiMqYQCRB8EBhgAEfctkX6vL+UF/UXGdGJEL/8GUrm/VBVgpUn05OL8zfP3A9vPqlEwGTIKlDSu+hCM7YSKFq4KYn9jD5PoBhMBaMdWIQb6l3XuN0NkZtC9CoEDGx4J35GcAdtX4B6urZ8fVej2FWbZB4tgFfna0xAOBaIDmINjpMsDUYhzRDK2jpkiwKUdcEka4l7pIk1BNnCe3W3EgSYF9yL21oIYi4r0IwOPM85FimQpNIxER4MrodY+BSf4bYoZgjnx+p4Qq/h18IyKhIk939PFY9zBfc3nwz7YBbUSHqNBp5L3lLLXFRUBFjrPN8wsF7Mfnfc6jPC5FwY4eRDlpyQMfbVPWf0F2uPxU8HXULSaPaEsmSVeZ8tboIYI1yG5x5c4qsLhXC4sy5JoWOORuJpLX+n3hd0i9miPuQuR5iaqd0XrEcmTb1A7blJxmv+xEu6g97276uH77cRX/3/AiPIyfLzeNKOfXMc5BxZMdiLp+yy/op86SAlaWYe7VZk9yxrtgpeLpo+h3gL14O0ZGe/MOTYQfcq1bgL8sUVup0cHSSyHj8=
  organization: thor
  space: prod
  on:
    repo: el-davo/linkcouch-screenshots-backend
